version: '2'

services:

    webapp:
        image: infrascielo/search-journals:stable
        restart: always
        hostname: webapp
        depends_on:
            - solrcontroller
        links:
            - solrcontroller:solrcontroller
        ports:
            - "80:80"
        environment:
            - SEARCH_SOLR_CORE=solr/articles
            - SEARCH_USE_HTTPS=false
            - SEARCH_SOLR_SERVER=solrcontroller:8080
            - COOKIE_POLICY_ENABLED=true
            - COOKIE_POLICY_SCRIPT_URL=https://static.scielo.org/js/cookiePolicy.min.js
            - REVENF_DOMAIN=search.revenf.org
            - SCL_DOMAIN=search.scielo.org

    solrcontroller:
        image: infrascielo/search-journal-iahx-controller:latest
        restart: always
        depends_on:
            - solr
        links:
            - solr:solr
        ports:
            - "8080:8080"

    solr:
        image: solr:8.5.1
        volumes:
            - ./solr/8.5.1/cores/solrdata:/var/solr
        ports:
            - 8983:8983/tcp
        command:
            - solr-precreate
            - articles
        environment:
            - SOLR_HEAP=4g
            - SOLR_JAVA_MEM="-Xms4g -Xmx4g"
            - SOLR_OPTS=-XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=75 -XX:+AggressiveOpts

